locate button:     user.locate_hover("button.png")
grab line left:    user.locate_grab_line("vertical")
grab line down:    user.locate_grab_line("horizontal")
move line left:    user.locate_line_move(-1)
move line right:   user.locate_line_move(1)