key(keypad_0):     user.foot_switch_key(0)
key(keypad_1):     user.foot_switch_key(1)
key(keypad_2):     user.foot_switch_key(2)
key(keypad_3):     user.foot_switch_key(3)
switch reversed:   user.foot_switch_scroll_reversed()